language: cpp

compiler: gcc

before_install:
  # g++4.8.1
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq

install:
  # g++4.8.1
  - sudo apt-get install -qq g++-4.8
  - export CXX="g++-4.8"
  - $CXX --version
  - sudo apt-get install cmake libglew-dev libudev-dev
  - wget http://ftp.de.debian.org/debian/pool/main/g/glew/libglew-dev_1.10.0-3_amd64.deb -O libglew-dev.deb && sudo dpkg -i libglew-dev.deb
  - ./get-deps.sh

script: mkdir -p build && cd build && cmake .. && make -j 8
    

